---
title: "Growth Accounting"
author: "Colin Pi"
date: '2018 6 3 '
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Penn World Dataset

```{r}
library(readxl)
penn_world <- read_excel("~/Documents/2017-18/ECON241/Final_Project/first_paper_assignment/Growth Accounting.xlsx", sheet = "Data")
suppressMessages(library(dplyr))
dataset_1 <- penn_world %>% 
  filter(country %in% c("United States", "Republic of Korea", "Japan")) %>%
  select(country,year,rgdpe,rgdpo,pop,emp,hc,ccon,cda,
         cgdpe,cgdpo,rgdpna,rkna,labsh,delta,csh_c,csh_i,csh_g,csh_x,csh_m,csh_r)
```

## GDP per Worker and GDP per Capita

```{r}
per_capita <- function(argument){
  outcome <- dataset_1 %>% na.omit() %>% filter(country == argument) %>% 
    filter(year == max(year)) %>% group_by(country, year) %>% 
    summarize(rgdpna_emp = rgdpna/emp, rgdpna_pc = rgdpna/pop)
  return(outcome)
}
gdp_per_capita <- lapply(c("Japan","Republic of Korea","United States"), per_capita) %>% 
  bind_rows()
knitr::kable(gdp_per_capita)
```

## Growth Accounting

```{r}
growth_rate_func <- function(nation){
  subset <- dataset_1 %>% filter(country == nation) %>% na.omit() %>% 
    mutate(gdpPercap = rgdpna/emp, capPercap = rkna/emp)
  output <- subset %>% group_by(country) %>% 
    summarize(`Output GR`= 
                ((gdpPercap[nrow(subset)]/gdpPercap[1])^(1/(year[nrow(subset)]-year[1]))-1)*100,
              `Physical Capital GR`=
                ((capPercap[nrow(subset)]/capPercap[1])^(1/(year[nrow(subset)]-year[1]))-1)*100,
              `Human Capital GR` = 
                ((hc[nrow(subset)]/hc[1])^(1/(year[nrow(subset)]-year[1]))-1)*100,
              `Productivity GR` =
                `Output GR` - 1/3*`Physical Capital GR` - 2/3*`Human Capital GR`) %>% 
    mutate(`Productivity's Share` = 
             ((`Productivity GR`)/`Output GR`)*100,
           `Human Capital's Share` = 
             ((2/3*`Human Capital GR`)/`Output GR`)*100,
           `Physical Capital's Share` = 
             ((1/3*`Physical Capital GR`)/`Output GR`)*100)
  return(output)
}

growth_rate <- lapply(c("Republic of Korea","United States","Japan"), 
                      growth_rate_func) %>% bind_rows()
knitr::kable(growth_rate[,1:5])
knitr::kable(growth_rate[,c(1,6:8)])
```

